framework:
    messenger:
        default_bus: messenger.bus.query
        buses:
            messenger.bus.command:
                default_middleware: false
                middleware:
                    - handle_message

            messenger.bus.query: ~